CREATE TABLE SESSIONS
(
    PRIMARY_ID            CHAR(36) NOT NULL,
    SESSION_ID            CHAR(36) NOT NULL,
    CREATION_TIME         BIGINT   NOT NULL,
    LAST_ACCESS_TIME      BIGINT   NOT NULL,
    MAX_INACTIVE_INTERVAL INT      NOT NULL,
    EXPIRY_TIME           BIGINT   NOT NULL,
    PRINCIPAL_NAME        VARCHAR(100),
    CONSTRAINT SESSIONS_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SESSIONS_IX1 ON SESSIONS (SESSION_ID);
CREATE INDEX SESSIONS_IX2 ON SESSIONS (EXPIRY_TIME);
CREATE INDEX SESSIONS_IX3 ON SESSIONS (PRINCIPAL_NAME);

CREATE TABLE SESSIONS_ATTRIBUTES
(
    SESSION_PRIMARY_ID CHAR(36)     NOT NULL,
    ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES    BYTEA        NOT NULL,
    CONSTRAINT SESSIONS_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SESSIONS_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SESSIONS (PRIMARY_ID) ON DELETE CASCADE
);